### PR TITLE
Send MetaKG to threads

### PR DESCRIPTION
**Pull request by rjawesome**
This creates a MetaKG during the cron job and saves the operations. It then sends the operations to each thread. This allows the time to create MetaKG to go from around **500ms** to **1ms**.
This also writes smartapi specs to redis, so they can be used in query graph handler for finding unregistered APIs (prevents read-write conflicts).

### CODE REVIEW

**Comment by tokebe** [comment]
@rjawesome Please re-review related PRs and fix with new merge conflicts -- I'll review and merge once you have.

**Comment by colleenXu** [comment]
It may be helpful to link this/related PRs to the issue that they address?

**Comment by tokebe** [comment]
@colleenXu Implementation covers performance improvements not currently in an issue, as well as addressing https://github.com/biothings/biothings_explorer/issues/703

**Comment by rjawesome** [comment]
All Associated PRs should be fixed
https://github.com/biothings/biothings_explorer/pull/814 (new)
https://github.com/biothings/bte_trapi_query_graph_handler/pull/183
https://github.com/biothings/smartapi-kg.js/pull/87

**Comment by tokebe** [comment]
@rjawesome Just about ready to merge, the only thing I'm a bit confused about is the new data/kg.json file. It doesn't appear to be used in related PRs? Am I mistaken, or should it be removed?

**Comment by rjawesome** [comment]
You are correct about kg/data.json (it's removed). I also changed it so the specs would be passed through the thread (similar to MetaKG) instead of through redis.

**Pull request merged**
